<?php if (!defined('ABSPATH')) { exit; }

/**
 *  Register and handle shortcodes.
 */
class SS_Shortcodes
{
    /**
     *  Main shortcode name.
     *
     *  @const string
     */
    const MAIN_SHORTCODE = 'cardz';

    /**
     *  Default constructor
     */
    public function __construct()
    {
        add_shortcode(self::MAIN_SHORTCODE, array(&$this, 'speedo_social_stream'));
    }
    
    /**
     *  Default shortcode.
     */
    public function speedo_social_stream($atts, $content = '')
    {
        global $post, $ss_shortcode_count;
        
        /**
         *  Filters the shortcode attributes.
         *
         *  @since 1.0.12
         *
         *  @param array $atts Attributes passed to shortocode.
         */
        $atts = apply_filters('cardz_filter_shortcode_atts', shortcode_atts(array
        (
            'id' => 'cardz-social-' . (++$ss_shortcode_count),
            'use' => ''
        ), $atts));
        
        extract($atts);
        
        if ($use != '' && $use !== 'none')
        {
            if (is_numeric($use))
            {
                $post = get_post($use);
            }
            else
            {
                $post = ss_get_post_by_slug($use, array('post_type' => SS_Post_Type::POST_TYPE));
            }
        }
        
        if (empty($post))
        {
            return '';
        }
        
        //$options = SS_Data()->get_options();
        $options = '';
        $stream_css_data = SS_Data()->get_option('ss-css-data', '');
        
        $data = get_post_meta($post->ID, 'ss-css-data', true);
        
        $loading_img = SS_PURL .'/content/js/skins/assets/images/loader_dark.svg';
        
        $html_value = <<<HTML
            <div id="{$id}" class="cardz-social {$id}" data-ss-name="{$use}"><img src="{$loading_img}" class="loader" style="display: block; margin: 0 auto; width="30" height="30" /></div>
            <style type="text/css">
                {$stream_css_data}
            </style>
            <script>
                jQuery.get(ss_urls.ajaxurl + '?action=ss-get-feed-data&use={$use}', function (data)
                {
                    jQuery('#{$id} img.loader').remove();
                    cardz_instances['{$use}'] = jQuery('.{$id}').cardZSocial(data);
                });
            </script>
HTML;

        /**
         *  Filters the HTML generated by the shortcode.
         *
         *  @since 1.0.12
         *
         *  @param string $html_value The HTML value.
         */
        return apply_filters('cardz_filter_shortcode_html', $html_value);
    }
}

$ss_shortcodes = new SS_Shortcodes();